query($where: QuestionWhereUniqueInput!) {
  question(where: $where) {
    id
    question
    answer {
      id
      title
    }      
    wrongAnswer {
      id
      title
    }
    course {
      id
      name
    }
  }
}
